CPPFLAGS=-O0 -g2 -Wall -c -fmessage-length=0 
LDLIBS=-lopengl32 -lglu32 -lglut32 -lglew32
EXEC_NAME=tp1.exe

all : $(EXEC_NAME)

$(EXEC_NAME): main.cpp
	g++ -g  -o ${EXEC_NAME} main.cpp $(LDLIBS)

clean :
	rm -f *.exe 
