LDLIBS=-lopencv_videoio342 -lopencv_imgproc342 -lopencv_highgui342 -lopencv_imgcodecs342 
EXEC_NAME=colorswitcher.exe

all : $(EXEC_NAME)

$(EXEC_NAME): colorswitcher.cpp
	g++ -o $(EXEC_NAME) colorswitcher.cpp $(LDLIBS)

clean :
	rm *.exe
